#!/bin/bash

# 명령어 실패 시 스크립트 종료
set -euo pipefail

# 로그 출력 함수
log() {
echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

# 에러 발생 시 로그와 함께 종료하는 함수
error() {
log "Error on line $1"
exit 1
}

trap 'error $LINENO' ERR

log "스크립트 실행 시작."

# docker network 생성
if docker network ls --format '{{.Name}}' | grep -q '^nansan-network$'; then
log "Docker network named 'nansan-network' is already existed."
else
log "Docker network named 'nansan-network' is creating..."
docker network create --driver bridge nansan-network
fi

cd insight || { echo "디렉토리 변경 실패"; exit 1; }

# 기존 redis 이미지를 삭제하고 새로 빌드
log "insight image remove and build."
docker rmi insight:latest || true
docker build -t insight:latest .

# 필요한 환경변수를 Vault에서 가져오기
log "Get credential data from vault..."

TOKEN_RESPONSES=$(curl -s --request POST \
--data "{\"role_id\":\"${ROLE_ID}\", \"secret_id\":\"${SECRET_ID}\"}" \
https://vault.nansan.site/v1/auth/approle/login)

CLIENT_TOKEN=$(echo "$TOKEN_RESPONSES" | jq -r '.auth.client_token')

SECRET_RESPONSE=$(curl -s --header "X-Vault-Token: ${CLIENT_TOKEN}" \
--request GET https://vault.nansan.site/v1/kv/data/auth)

REDISINSIGHT_USER=$(echo "$SECRET_RESPONSE" | jq -r '.data.data.insight.username')
REDISINSIGHT_PASSWORD=$(echo "$SECRET_RESPONSE" | jq -r '.data.data.insight.password')
RI_ENCRYPTION_KEY=$(echo "$SECRET_RESPONSE" | jq -r '.data.data.insight.key')

# Docker로 insight 서비스 실행
log "Execute insight..."
docker run -d \
  --name insight \
  --restart unless-stopped \
  -p 8084:8001 \
  -e REDISINSIGHT_AUTH=true \
  -e REDISINSIGHT_USER=${REDISINSIGHT_USER} \
  -e REDISINSIGHT_PASSWORD=${REDISINSIGHT_PASSWORD} \
  -e RI_ENCRYPTION_KEY=${RI_ENCRYPTION_KEY} \
  -v /var/insight:/data \
  --network nansan-network \
  insight:latest

echo "작업이 완료되었습니다."